---
title: "Discussion 7 Exercise Solution"
author: "Huaiyu"
date: "October 31, 2019"
output: html_document
---
####Exercise
As question 2 in midterm, to test if your friend knows classical music, you setup the following game: you play a random piece of classicial music and ask your friend to guess the author; if she guesses correctly, you play a new piece, and so on, until she makes a mistake. Assume that your friend has the same probability $\theta$ of correctly guessing the author of a piece of classical music and that each guess is independent. Thus, if in the i-th round of the game she got $y_i$ correct guesses, the likelihood is $P(y_i|\theta) = \theta^{y_i}(1-\theta)$. You repeated this game for $n = 10$ rounds and overall, your friend got $y_i = 4, 1, 1, 4, 2, 3, 3, 2, 5, 2$ correct guesses. Assuming prior is $\theta \sim Beta(1/2, 0)$ and posterior is $\theta|y \sim Beta(\sum y_i + 1/2, n)$, please conduct model checking with test function $|y^{0.9} - t^{0.5}| - |y^{0.1} - t^{0.5}|$ where $t^{0.5}$ is a quantile of t.

```{r}
y <- c(4, 1, 1, 4, 2, 3, 3, 2, 5, 2)
N <- 10000

theta_s <- matrix(nrow = N, ncol = length(y))
yrep <- matrix(nrow = N, ncol = length(y))

for (j in 1:length(y)) {
  theta_s[,j] <- rbeta(N, sum(y) + 1/2, length(y))
  yrep[,j] <- rgeom(N, theta_s[,j])
}

theta_s <- theta_s/(1-theta_s) #geometric distribution: mean = theta/(1-theta)
# T(y, t) := |y^(.9) - t^(.5)| - |y^(.1) - t^(.5)|, t^(a) is a-quantile of t
tm <- apply(theta_s, 1, median) # t^(.5)
s <- quantile(y, c(.1, .9))
Tdata <- abs(s[2] - tm) - abs(s[1] - tm)

s <- abs(t(apply(yrep, 1, quantile, c(.1, .9))) - tm)
Trep <- s[,2] - s[,1]
mean(Trep >= Tdata)
```